"""add kamis code fields to items

Revision ID: 59633ef133e1
Revises: 75ee978040c8
Create Date: 2026-04-28 11:03:13.755376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59633ef133e1'
down_revision: Union[str, Sequence[str], None] = '75ee978040c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 기존 rows가 있으므로 server_default='' 로 추가 후 default 제거
    op.add_column('items', sa.Column('kamis_category_code', sa.String(length=10), nullable=False, server_default=''))
    op.add_column('items', sa.Column('kamis_item_code', sa.String(length=20), nullable=False, server_default=''))
    op.add_column('items', sa.Column('kamis_kind_code', sa.String(length=20), nullable=False, server_default=''))
    op.add_column('items', sa.Column('kamis_rank', sa.String(length=20), nullable=True))
    op.alter_column('items', 'kamis_category_code', server_default=None)
    op.alter_column('items', 'kamis_item_code', server_default=None)
    op.alter_column('items', 'kamis_kind_code', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'kamis_rank')
    op.drop_column('items', 'kamis_kind_code')
    op.drop_column('items', 'kamis_item_code')
    op.drop_column('items', 'kamis_category_code')
    # ### end Alembic commands ###
